#!/usr/bin/env perl
# tab2fasta
# one-liner: perl -naF'\t' -e 'print">$F[0]\n$F[1]\n"'
#            perl -naF'\t' -e '$F[1]=~s/(\S{60})/$&\n/gs;print">$F[0]\n$F[1]\n"'
while(<>) {
    chomp;
    my ($h, $s) = split /\t+/;
    $s =~ s/\S{60}/$&\n/sg;
    print STDOUT ">$h\n$s\n";
}
